# kubectl apply -f ....yaml

apiVersion: v1
kind: Service
metadata:
  name: svc-ms-ip
  namespace : development
spec:
  selector:
    app: back-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
