# pour générer le contenu de dockerconfigjson :
# cat /home/etudiant/snap/docker/current/.docker/config.json | base64

# Executer le script
# kubectl apply -f secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: private-registry-key
  namespace: development
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC41NC41Ni4zOTo1MDAwIjogewoJCQkiYXV0aCI6ICJaWFIxWkdsaGJuUTZaWFIxWkdsaGJuUT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
