/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import static spark.Spark.*;

public class App {
    
    public static void main(String[] args) {
        // Définit le port sur lequel le serveur écoutera les requêtes
        port(8080);

        // Définit la route GET /api/v1/ip pour récupérer l'adresse IP du Pod
        get("/api/v1/ip", (request, response) -> {
            // Appel à une méthode pour obtenir l'adresse IP du Pod
            String ip = getPodIP();
            // Renvoie l'adresse IP dans la réponse HTTP
            return "{\"ip\":\"" + ip + "\"}";
        });
    }

    // Méthode pour obtenir l'adresse IP du Pod
    private static String getPodIP() {
        try {
            // Utilise InetAddress pour obtenir l'adresse IP locale du Pod
            java.net.InetAddress address = java.net.InetAddress.getLocalHost();
            return address.getHostAddress();
        } catch (java.net.UnknownHostException e) {
            // En cas d'erreur, renvoie "Unknown"
            e.printStackTrace();
            return "Unknown";
        }
    }
}
